[package]
name = "netstrat"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[build-dependencies]
gcc = "0.3"

[dependencies]
cast = "0.2"
error-chain = "0.11"
libc = "0.2"
nix = "0.10"
pnet = "0.21"
pnet_macros_support = "0.21"

[dependencies.pnetlink]
path = "../pnetlink"
